"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

DATA_FILES = ['img/1.ppm','img/2.ppm','img/3.ppm','img/4.ppm']

setup(
    name="PhotoGrabber",
    data_files=DATA_FILES,
    setup_requires=['py2app'],
    app=['pg.py'],
    options=dict(py2app=dict(argv_emulation=True,iconfile='pg.icns')),
)
